In [1]:
import pandas as pd
pd.set_option('display.max_columns', 500)
from urllib.parse import urlparse #get domain from url
import numpy as np
import sqlalchemy
import re
import glob

# Koneksi Database

In [2]:
# Import dataframe into MySQL
database_username = 'sigama_tender'
database_password = '5sWrx53vQPcU'
database_ip       = 'sv2.ecc.co.id'
database_name     = 'sigama_tender'
database_connection = sqlalchemy.create_engine('mysql+mysqlconnector://{0}:{1}@{2}/{3}'.
                                               format(database_username, database_password, 
                                                      database_ip, database_name))
database_connection

Engine(mysql+mysqlconnector://sigama_tender:***@sv2.ecc.co.id/sigama_tender)

In [3]:
# Load to DB

# tabel_peserta_tender.to_sql(con=database_connection, name='peserta_tender',if_exists='append',index=False, chunksize=1000)

In [4]:
pengumuman_excel_0_100 = []
data_excel_0_100 = []

for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\rizky\0_Rizky\lengkap_525(pu)\pengumuman_525.csv'):
    pengumuman_excel_0_100.append(each_file)
for file_number in range(len(pengumuman_excel_0_100)):
    data_excel_0_100.append(pd.read_csv(pengumuman_excel_0_100[file_number]))
data_excel_pengumuman_0_100 = pd.concat(data_excel_0_100, ignore_index=True)

In [5]:
data_excel_pengumuman_0_100

,url_lpse,id_tender,id_rup,nama_tahapan,status,status_spse,status_evaluasi,alasan,nama_paket,sumber_dana,tgl_pembuatan,k_l_pd,satker,jenis_tender,metode_pengadaan,metode_pemilihan,metode_evaluasi,tahun_anggaran,nilai_kontrak,nilai_pagu,nilai_hps,cara_bayar,lokasi_pekerjaan,kualifikasi,detail_kualifikasi,jumlah_peserta,link_pengumuman_error
0,https://lpse.pu.go.id/eproc4/lelang,82617064,37095704.0,Pengumuman Pascakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pemeliharaan Berkala Sungai Cikapundung,APBN,15-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,OPERASI DAN PEMELIHARAAN SUMBER DAYA AIR CITARUM,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Tender,Harga Terendah Sistem Gugur,2023.0,NaN,"5.000.000.000,00","4.999.989.000,00",Harga Satuan,Kabupaten Bandung - Bandung (Kota),Kecil,<strong>Persyaratan Kualifikasi Administrasi/L...,36 peserta,NaN
1,https://lpse.pu.go.id/eproc4/lelang,82608064,37824340.0,Pengumuman Prakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pengawasan Teknis Jalan dan Jembatan Halmahera...,APBN,15-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,486112,Jasa Konsultansi Badan Usaha Konstruksi,Prakualifikasi Dua File,Seleksi,Kualitas dan Biaya,2023.0,NaN,"1.651.595.000,00","1.651.595.000,00",Waktu Penugasan,KAB. HALMAHERA TENGAH - Halmahera Tengah (Kab.),NaN,"<strong>Persyaratan Kualifikasi</strong>, \n, ...",7 peserta,NaN
2,https://lpse.pu.go.id/eproc4/lelang,82607064,37824339.0,Pengumuman Prakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pengawasan Teknis Jalan dan Jembatan Tidore Ke...,APBN,15-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,486112,Jasa Konsultansi Badan Usaha Konstruksi,Prakualifikasi Dua File,Seleksi,Kualitas dan Biaya,2023.0,NaN,"1.916.280.000,00","1.916.280.000,00",Waktu Penugasan,KOTA TIDORE KEPULAUAN - Tidore Kepulauan (Kota),NaN,"<strong>Persyaratan Kualifikasi</strong>, \n, ...",9 peserta,NaN
3,https://lpse.pu.go.id/eproc4/lelang,82605064,37824338.0,Pengumuman Prakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pengawasan Teknis Jalan dan Jembatan Pulau Mor...,APBN,15-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,486112,Jasa Konsultansi Badan Usaha Konstruksi,Prakualifikasi Dua File,Seleksi,Kualitas dan Biaya,2023.0,NaN,"2.025.317.000,00","2.025.317.000,00",Waktu Penugasan,KAB. PULAU MOROTAI - Pulau Morotai (Kab.),NaN,"<strong>Persyaratan Kualifikasi</strong>, \n, ...",9 peserta,NaN
4,https://lpse.pu.go.id/eproc4/lelang,82581064,37735487.0,Pengumuman Pascakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pembangunan Tanggul Permanen Sungai Cikundul d...,APBN,14-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,498134,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Tender,Harga Terendah Sistem Gugur,2023.0,NaN,"9.000.000.000,00","8.999.998.000,00",Harga Satuan,KAB. CIANJUR - Cianjur (Kab.),Kecil,<strong>Persyaratan Kualifikasi Administrasi/L...,39 peserta,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60802,https://lpse.pu.go.id/eproc4/lelang,7064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Pembangunan Rusunawa Kota Bekasi Lokasi Mabes ...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60803,https://lpse.pu.go.id/eproc4/lelang,6064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Pembangunan Rusunawa Kota Bandung Lokasi Kodam...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60804,https://lpse.pu.go.id/eproc4/lelang,5064,NaN,Tender Gagal,Tender Gagal,spse 3,NaN,NaN,Pembangunan Rusunawa Kabupaten Bogor Lokasi Ko...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60805,https://lpse.pu.go.id/eproc4/lelang,4064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Pembangunan Rusunawa Kota Banda Aceh Lokasi Ko...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60806,https://lpse.pu.go.id/eproc4/lelang,19947064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Rehabilitasi Jalan Bangkae - Pangkajene Sidrap...,APBN,26-10-2016,Kementerian Pekerjaan Umum dan Perumahan Rakyat,PELAKSANAAN JALAN NASIONAL WILAYAH II PROVINSI...,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2007.0,"27.224.510.243,00","32.800.000.000,00","32.725.000.000,00",Harga Satuan,Sidrap - Sidenreng Rappang (Kab.),Kecil,"<table class=""table table-sm"">\n<tbody><tr val...",60 peserta,NaN

In [6]:
# # import path all csv data
# pengumuman_excel_0_100 = []
# pengumuman_excel_101_200 = []
# pengumuman_excel_201_300 = []
# pengumuman_excel_301_400 = []
# pengumuman_excel_401_500 = []
# pengumuman_excel_501_600 = []
# pengumuman_excel_601_700 = []

# pengumuman_csv_0_100 = []
# pengumuman_csv_101_200 = []
# pengumuman_csv_201_300 = []
# pengumuman_csv_301_400 = []
# pengumuman_csv_401_500 = []
# pengumuman_csv_501_600 = []
# pengumuman_csv_601_700 = []

# data_excel_0_100 = []
# data_csv_0_100 = []
# data_excel_101_200 = []
# data_csv_101_200 = []
# data_excel_201_300 = []
# data_csv_201_300 = []
# data_excel_301_400 = []
# data_csv_301_400 = []
# data_excel_401_500 = []
# data_csv_401_500 = []
# data_excel_501_600 = []
# data_csv_501_600 = []
# data_excel_601_700 = []
# data_csv_601_700 = []

# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\0 - 100\*.xlsx'):
#     pengumuman_excel_0_100.append(each_file)
# for file_number in range(len(pengumuman_excel_0_100)):
#     data_excel_0_100.append(pd.read_excel(pengumuman_excel_0_100[file_number]))
# data_excel_pengumuman_0_100 = pd.concat(data_excel_0_100, ignore_index=True)
    
# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\0 - 100\*.csv'):
#     pengumuman_csv_0_100.append(each_file)
# for file_number in range(len(pengumuman_csv_0_100)):
#     data_csv_0_100.append(pd.read_csv(pengumuman_csv_0_100[file_number]))
# data_csv_pengumuman_0_100 = pd.concat(data_csv_0_100, ignore_index=True)

# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\101 - 200\*.xlsx'):
#     pengumuman_excel_101_200.append(each_file)
# for file_number in range(len(pengumuman_excel_101_200)):
#     data_excel_101_200.append(pd.read_excel(pengumuman_excel_101_200[file_number]))
# data_excel_pengumuman_101_200 = pd.concat(data_excel_101_200, ignore_index=True)
    
# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\101 - 200\*.csv'):
#     pengumuman_csv_101_200.append(each_file)
# for file_number in range(len(pengumuman_csv_101_200)):
#     data_csv_101_200.append(pd.read_csv(pengumuman_csv_101_200[file_number]))
# data_csv_pengumuman_101_200 = pd.concat(data_csv_101_200, ignore_index=True)

# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\201 - 300\*.xlsx'):
#     pengumuman_excel_201_300.append(each_file)
# for file_number in range(len(pengumuman_excel_201_300)):
#     data_excel_201_300.append(pd.read_excel(pengumuman_excel_201_300[file_number]))
# data_excel_pengumuman_201_300 = pd.concat(data_excel_201_300, ignore_index=True)
    
# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\201 - 300\*.csv'):
#     pengumuman_csv_201_300.append(each_file)
# for file_number in range(len(pengumuman_csv_201_300)):
#     data_csv_201_300.append(pd.read_csv(pengumuman_csv_201_300[file_number]))
# data_csv_pengumuman_201_300 = pd.concat(data_csv_201_300, ignore_index=True)

# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\301 - 400\*.xlsx'):
#     pengumuman_excel_301_400.append(each_file)
# for file_number in range(len(pengumuman_excel_301_400)):
#     data_excel_301_400.append(pd.read_excel(pengumuman_excel_301_400[file_number]))
# data_excel_pengumuman_301_400 = pd.concat(data_excel_301_400, ignore_index=True)
    
# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\301 - 400\*.csv'):
#     pengumuman_csv_301_400.append(each_file)
# for file_number in range(len(pengumuman_csv_301_400)):
#     data_csv_301_400.append(pd.read_csv(pengumuman_csv_301_400[file_number]))
# data_csv_pengumuman_301_400 = pd.concat(data_csv_301_400, ignore_index=True)

# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\401 - 500\*.xlsx'):
#     pengumuman_excel_401_500.append(each_file)
# for file_number in range(len(pengumuman_excel_401_500)):
#     data_excel_401_500.append(pd.read_excel(pengumuman_excel_401_500[file_number]))
# data_excel_pengumuman_401_500 = pd.concat(data_excel_401_500, ignore_index=True)
    
# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\401 - 500\*.csv'):
#     pengumuman_csv_401_500.append(each_file)
# for file_number in range(len(pengumuman_csv_401_500)):
#     data_csv_401_500.append(pd.read_csv(pengumuman_csv_401_500[file_number]))
# data_csv_pengumuman_401_500 = pd.concat(data_csv_401_500, ignore_index=True)

# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\501 - 600\*.xlsx'):
#     pengumuman_excel_501_600.append(each_file)
# for file_number in range(len(pengumuman_excel_501_600)):
#     data_excel_501_600.append(pd.read_excel(pengumuman_excel_501_600[file_number]))
# data_excel_pengumuman_501_600 = pd.concat(data_excel_501_600, ignore_index=True)
    
# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\501 - 600\*.csv'):
#     pengumuman_csv_501_600.append(each_file)
# for file_number in range(len(pengumuman_csv_501_600)):
#     data_csv_501_600.append(pd.read_csv(pengumuman_csv_501_600[file_number]))
# data_csv_pengumuman_501_600 = pd.concat(data_csv_501_600, ignore_index=True)

# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\601 - 700\*.xlsx'):
#     pengumuman_excel_601_700.append(each_file)
# for file_number in range(len(pengumuman_excel_601_700)):
#     data_excel_601_700.append(pd.read_excel(pengumuman_excel_601_700[file_number]))
# data_excel_pengumuman_601_700 = pd.concat(data_excel_601_700, ignore_index=True)
    
# for each_file in glob.glob(r'D:\Data Engineer - Beecons\Document\pengumuman\601 - 700\*.csv'):
#     pengumuman_csv_601_700.append(each_file)
# for file_number in range(len(pengumuman_csv_601_700)):
#     data_csv_601_700.append(pd.read_csv(pengumuman_csv_601_700[file_number]))
# data_csv_pengumuman_601_700 = pd.concat(data_csv_601_700, ignore_index=True)

# df_concat = pd.concat([data_excel_pengumuman_0_100, data_csv_pengumuman_0_100,
#                             data_excel_pengumuman_101_200, data_csv_pengumuman_101_200,
#                             data_excel_pengumuman_201_300, data_csv_pengumuman_201_300,
#                             data_excel_pengumuman_301_400, data_csv_pengumuman_301_400,
#                             data_excel_pengumuman_401_500, data_csv_pengumuman_401_500,
#                             data_excel_pengumuman_501_600, data_csv_pengumuman_501_600,
#                             data_excel_pengumuman_601_700, data_csv_pengumuman_601_700], ignore_index=True)

In [7]:
df_concat = data_excel_pengumuman_0_100.copy()
df_concat

,url_lpse,id_tender,id_rup,nama_tahapan,status,status_spse,status_evaluasi,alasan,nama_paket,sumber_dana,tgl_pembuatan,k_l_pd,satker,jenis_tender,metode_pengadaan,metode_pemilihan,metode_evaluasi,tahun_anggaran,nilai_kontrak,nilai_pagu,nilai_hps,cara_bayar,lokasi_pekerjaan,kualifikasi,detail_kualifikasi,jumlah_peserta,link_pengumuman_error
0,https://lpse.pu.go.id/eproc4/lelang,82617064,37095704.0,Pengumuman Pascakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pemeliharaan Berkala Sungai Cikapundung,APBN,15-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,OPERASI DAN PEMELIHARAAN SUMBER DAYA AIR CITARUM,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Tender,Harga Terendah Sistem Gugur,2023.0,NaN,"5.000.000.000,00","4.999.989.000,00",Harga Satuan,Kabupaten Bandung - Bandung (Kota),Kecil,<strong>Persyaratan Kualifikasi Administrasi/L...,36 peserta,NaN
1,https://lpse.pu.go.id/eproc4/lelang,82608064,37824340.0,Pengumuman Prakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pengawasan Teknis Jalan dan Jembatan Halmahera...,APBN,15-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,486112,Jasa Konsultansi Badan Usaha Konstruksi,Prakualifikasi Dua File,Seleksi,Kualitas dan Biaya,2023.0,NaN,"1.651.595.000,00","1.651.595.000,00",Waktu Penugasan,KAB. HALMAHERA TENGAH - Halmahera Tengah (Kab.),NaN,"<strong>Persyaratan Kualifikasi</strong>, \n, ...",7 peserta,NaN
2,https://lpse.pu.go.id/eproc4/lelang,82607064,37824339.0,Pengumuman Prakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pengawasan Teknis Jalan dan Jembatan Tidore Ke...,APBN,15-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,486112,Jasa Konsultansi Badan Usaha Konstruksi,Prakualifikasi Dua File,Seleksi,Kualitas dan Biaya,2023.0,NaN,"1.916.280.000,00","1.916.280.000,00",Waktu Penugasan,KOTA TIDORE KEPULAUAN - Tidore Kepulauan (Kota),NaN,"<strong>Persyaratan Kualifikasi</strong>, \n, ...",9 peserta,NaN
3,https://lpse.pu.go.id/eproc4/lelang,82605064,37824338.0,Pengumuman Prakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pengawasan Teknis Jalan dan Jembatan Pulau Mor...,APBN,15-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,486112,Jasa Konsultansi Badan Usaha Konstruksi,Prakualifikasi Dua File,Seleksi,Kualitas dan Biaya,2023.0,NaN,"2.025.317.000,00","2.025.317.000,00",Waktu Penugasan,KAB. PULAU MOROTAI - Pulau Morotai (Kab.),NaN,"<strong>Persyaratan Kualifikasi</strong>, \n, ...",9 peserta,NaN
4,https://lpse.pu.go.id/eproc4/lelang,82581064,37735487.0,Pengumuman Pascakualifikasi [...],NaN,spse 4.5,NaN,NaN,Pembangunan Tanggul Permanen Sungai Cikundul d...,APBN,14-12-2022,Kementerian Pekerjaan Umum dan Perumahan Rakyat,498134,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Tender,Harga Terendah Sistem Gugur,2023.0,NaN,"9.000.000.000,00","8.999.998.000,00",Harga Satuan,KAB. CIANJUR - Cianjur (Kab.),Kecil,<strong>Persyaratan Kualifikasi Administrasi/L...,39 peserta,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60802,https://lpse.pu.go.id/eproc4/lelang,7064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Pembangunan Rusunawa Kota Bekasi Lokasi Mabes ...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60803,https://lpse.pu.go.id/eproc4/lelang,6064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Pembangunan Rusunawa Kota Bandung Lokasi Kodam...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60804,https://lpse.pu.go.id/eproc4/lelang,5064,NaN,Tender Gagal,Tender Gagal,spse 3,NaN,NaN,Pembangunan Rusunawa Kabupaten Bogor Lokasi Ko...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60805,https://lpse.pu.go.id/eproc4/lelang,4064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Pembangunan Rusunawa Kota Banda Aceh Lokasi Ko...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60806,https://lpse.pu.go.id/eproc4/lelang,19947064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Rehabilitasi Jalan Bangkae - Pangkajene Sidrap...,APBN,26-10-2016,Kementerian Pekerjaan Umum dan Perumahan Rakyat,PELAKSANAAN JALAN NASIONAL WILAYAH II PROVINSI...,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2007.0,"27.224.510.243,00","32.800.000.000,00","32.725.000.000,00",Harga Satuan,Sidrap - Sidenreng Rappang (Kab.),Kecil,"<table class=""table table-sm"">\n<tbody><tr val...",60 peserta,NaN

## Check Duplicated Data

In [8]:
# must drop duplicate tender if value is the same
# df_concat.drop_duplicates(subset=['nama_paket'], inplace=True, ignore_index=True)

# duplicate id tender with different package name
duplicat_count = df_concat[df_concat.duplicated(subset='id_tender', keep=False)]
print('nilai duplikatnya :', len(duplicat_count))

df_concat[df_concat.duplicated(subset='id_tender', keep=False)].reset_index(drop=True)

nilai duplikatnya : 0

Empty DataFrame
Columns: [url_lpse, id_tender, id_rup, nama_tahapan, status, status_spse, status_evaluasi, alasan, nama_paket, sumber_dana, tgl_pembuatan, k_l_pd, satker, jenis_tender, metode_pengadaan, metode_pemilihan, metode_evaluasi, tahun_anggaran, nilai_kontrak, nilai_pagu, nilai_hps, cara_bayar, lokasi_pekerjaan, kualifikasi, detail_kualifikasi, jumlah_peserta, link_pengumuman_error]
Index: []

# Kolom id duplikat

In [9]:
# adding id_duplikat
df_concat.insert(1, 'id_duplikat', df_concat['id_tender'])
df_concat['id_duplikat'] = df_concat['id_duplikat'].astype('string')
df_concat.loc[df_concat[df_concat['id_duplikat'].duplicated(keep=False)].index, 'id_duplikat'] = df_concat['id_duplikat'] + '.' + df_concat.groupby('id_duplikat').cumcount().add(10).astype(str)

# check duplicated value only
table_tmp = df_concat[df_concat.duplicated(subset='id_tender', keep=False)].sort_values(by=['id_tender']).reset_index(drop=True)

In [10]:
table_tmp[table_tmp.id_tender==1001]

Empty DataFrame
Columns: [url_lpse, id_duplikat, id_tender, id_rup, nama_tahapan, status, status_spse, status_evaluasi, alasan, nama_paket, sumber_dana, tgl_pembuatan, k_l_pd, satker, jenis_tender, metode_pengadaan, metode_pemilihan, metode_evaluasi, tahun_anggaran, nilai_kontrak, nilai_pagu, nilai_hps, cara_bayar, lokasi_pekerjaan, kualifikasi, detail_kualifikasi, jumlah_peserta, link_pengumuman_error]
Index: []

In [11]:
table_tmp.to_excel('tes.xlsx', index=False)

In [12]:
table_tmp[table_tmp.id_tender == 2828362]

Empty DataFrame
Columns: [url_lpse, id_duplikat, id_tender, id_rup, nama_tahapan, status, status_spse, status_evaluasi, alasan, nama_paket, sumber_dana, tgl_pembuatan, k_l_pd, satker, jenis_tender, metode_pengadaan, metode_pemilihan, metode_evaluasi, tahun_anggaran, nilai_kontrak, nilai_pagu, nilai_hps, cara_bayar, lokasi_pekerjaan, kualifikasi, detail_kualifikasi, jumlah_peserta, link_pengumuman_error]
Index: []

In [13]:
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60807 entries, 0 to 60806
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   url_lpse               60807 non-null  object
 1   id_duplikat            60807 non-null  string
 2   id_tender              60807 non-null  int64
 3   id_rup                 26085 non-null  float64
 4   nama_tahapan           60806 non-null  object
 5   status                 11483 non-null  object
 6   status_spse            60807 non-null  object
 7   status_evaluasi        8863 non-null   object
 8   alasan                 16624 non-null  object
 9   nama_paket             60807 non-null  object
 10  sumber_dana            59051 non-null  object
 11  tgl_pembuatan          59102 non-null  object
 12  k_l_pd                 60804 non-null  object
 13  satker                 59101 non-null  object
 14  jenis_tender           60807 non-null  object
 15  metode_pengadaan       60807 non-null  object
 16  metode_pemilihan       60807 non-null  object
 17  metode_evaluasi        60807 non-null  object
 18  tahun_anggaran         60805 non-null  float64
 19  nilai_kontrak          42743 non-null  object
 20  nilai_pagu             59102 non-null  object
 21  nilai_hps              59102 non-null  object
 22  cara_bayar             59102 non-null  object
 23  lokasi_pekerjaan       58251 non-null  object
 24  kualifikasi            30920 non-null  object
 25  detail_kualifikasi     58961 non-null  object
 26  jumlah_peserta         59102 non-null  object
 27  link_pengumuman_error  1705 non-null   object
dtypes: float64(2), int64(1), object(24), string(1)
memory usage: 13.0+ MB

In [14]:
df_concat.id_duplikat.nunique()

60807

In [15]:
# LPSE file (to get LPSE id)
query_lpse = '''SELECT * FROM lpse'''
lpse_src = pd.read_sql_query(query_lpse, database_connection)

# Domain columns for Joining Table
lpse_src["domain"] = lpse_src["url"].apply(lambda row: urlparse(row).netloc)
lpse_src.drop_duplicates(subset=['url'], inplace=True)

In [16]:
lpse_src[lpse_src.url=='https://lpse.kemenparekraf.go.id/eproc4']

,id_lpse,id_wilayah,id_kategori,nama_lpse,url,versi,id_repo,latitude,longitude,alamat,status,foto,domain
675,740,3173,1,Kementerian Pariwisata dan Ekonomi Kreatif,https://lpse.kemenparekraf.go.id/eproc4,4.5u20220721,386,-6.178802,106.821814,Jl. Medan Merdeka Barat No. 17 Jakarta Pusat (...,1,kementerian_pariwisata_dan_ekonomi_kreatif,lpse.kemenparekraf.go.id

# Tabel Tender

In [17]:
tender_src = df_concat.copy()
tender_src.replace('http://203.176.182.190/eproc4', 'http://lpse.pematangsiantar.go.id/eproc4', inplace=True)
tender_src.replace('http://182.23.40.66/eproc4', 'http://lpse.kepyapenkab.go.id/eproc4', inplace=True)
tender_src.replace('http://34.101.253.122/eproc4', 'http://lpse.labura.go.id/eproc4', inplace=True)
tender_src.replace('http://103.22.250.210/eproc4', 'http://lpse.sumbarprov.go.id/eproc4', inplace=True)
tender_src.replace('http://103.131.61.17/eproc4', 'http://lpse.florestimurkab.go.id/eproc4', inplace=True)
tender_src.replace('http://103.78.38.146/eproc4', 'http://lpse.manokwarikab.go.id/eproc4', inplace=True)
# tender_src.replace('http://36.91.152.66/eproc4', 'http://lpse.manokwarikab.go.id/eproc4', inplace=True)
# tender_src.drop(tender_src[tender_src.id_tender.isin(harus_drop)].index, inplace=True)
# tender_src.reset_index(drop=True, inplace=True)
tender_src.tail()

,url_lpse,id_duplikat,id_tender,id_rup,nama_tahapan,status,status_spse,status_evaluasi,alasan,nama_paket,sumber_dana,tgl_pembuatan,k_l_pd,satker,jenis_tender,metode_pengadaan,metode_pemilihan,metode_evaluasi,tahun_anggaran,nilai_kontrak,nilai_pagu,nilai_hps,cara_bayar,lokasi_pekerjaan,kualifikasi,detail_kualifikasi,jumlah_peserta,link_pengumuman_error
60802,https://lpse.pu.go.id/eproc4/lelang,7064,7064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Pembangunan Rusunawa Kota Bekasi Lokasi Mabes ...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60803,https://lpse.pu.go.id/eproc4/lelang,6064,6064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Pembangunan Rusunawa Kota Bandung Lokasi Kodam...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60804,https://lpse.pu.go.id/eproc4/lelang,5064,5064,NaN,Tender Gagal,Tender Gagal,spse 3,NaN,NaN,Pembangunan Rusunawa Kabupaten Bogor Lokasi Ko...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60805,https://lpse.pu.go.id/eproc4/lelang,4064,4064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Pembangunan Rusunawa Kota Banda Aceh Lokasi Ko...,NaN,NaN,Penyediaan Perumahan Kementerian Perumahan Rakyat,NaN,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2010.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
60806,https://lpse.pu.go.id/eproc4/lelang,19947064,19947064,NaN,Tender Sudah Selesai,NaN,spse 3,NaN,NaN,Rehabilitasi Jalan Bangkae - Pangkajene Sidrap...,APBN,26-10-2016,Kementerian Pekerjaan Umum dan Perumahan Rakyat,PELAKSANAAN JALAN NASIONAL WILAYAH II PROVINSI...,Pekerjaan Konstruksi,Pascakualifikasi Satu File,Lelang Umum,Harga Terendah Sistem Gugur,2007.0,"27.224.510.243,00","32.800.000.000,00","32.725.000.000,00",Harga Satuan,Sidrap - Sidenreng Rappang (Kab.),Kecil,"<table class=""table table-sm"">\n<tbody><tr val...",60 peserta,NaN

In [18]:
tender_src[tender_src.jenis_tender.isnull()]

Empty DataFrame
Columns: [url_lpse, id_duplikat, id_tender, id_rup, nama_tahapan, status, status_spse, status_evaluasi, alasan, nama_paket, sumber_dana, tgl_pembuatan, k_l_pd, satker, jenis_tender, metode_pengadaan, metode_pemilihan, metode_evaluasi, tahun_anggaran, nilai_kontrak, nilai_pagu, nilai_hps, cara_bayar, lokasi_pekerjaan, kualifikasi, detail_kualifikasi, jumlah_peserta, link_pengumuman_error]
Index: []

In [19]:
tender_src.jenis_tender.value_counts()

Pekerjaan Konstruksi                           29979
Jasa Konsultansi Badan Usaha                   24065
Jasa Konsultansi Badan Usaha Konstruksi         2297
Pengadaan Barang                                1773
Jasa Konsultansi Perorangan                     1726
Jasa Lainnya                                     718
Jasa Konsultansi Badan Usaha Non Konstruksi      245
Pekerjaan Konstruksi Terintegrasi                  3
Jasa Konsultansi Perorangan Konstruksi             1
Name: jenis_tender, dtype: int64

In [20]:
# Create domain column
tender_src["domain"] = tender_src["url_lpse"].apply(lambda row: urlparse(row).netloc)

# Cleaning Package name
list_kolom = ['alasan', 'nama_paket', 'lokasi_pekerjaan', 'k_l_pd', 'satker']
for i in list_kolom:
    tender_src[i] = tender_src[i].str.strip(', -')

# Removing dot and comma sign
list_kolom = ['nilai_kontrak', 'nilai_pagu', 'nilai_hps']
for i in list_kolom:
    tender_src[i] = tender_src[i].str.replace('.', '', regex=True).str.replace(',', '.')

# Generating status column
tender_src['status_baru'] = 'Selesai'
tender_src.loc[(tender_src['status'] == 'Tender Ulang') | (tender_src['status_evaluasi'].isin(['Evaluasi Ulang', 'Seleksi Ulang'])) , 'status_baru'] = 'Ulang'
tender_src.loc[(tender_src['status'].isin(['Tender Gagal', 'Tender Gagal, Tender Ulang', 'Tender Batal'])) | (tender_src['status_evaluasi'] == 'Seleksi Gagal') , 'status_baru'] = 'Gagal'
tender_src.drop(columns='status', axis=1, inplace=True)
tender_src.rename(columns={'status_baru':'status'},inplace=True)
tender_src['nama_tahapan'] = tender_src['nama_tahapan'].replace('\[...]', '', regex=True)
print('STATUS\n' + str(tender_src.nama_tahapan.value_counts()))

# Tender's DataFrame
df_tender = tender_src.copy()
df_tender.rename(columns={'nama_paket':'nama_tender'}, inplace=True)

# Columns Selection
df_tender = df_tender[['id_tender', 'id_duplikat', 'domain', 
                       'nama_tender', 'jenis_tender', 'tahun_anggaran', 'metode_pemilihan', 
                       'metode_pengadaan', 'metode_evaluasi', 'nama_tahapan', 'alasan', 
                       'nilai_kontrak', 'kualifikasi', 'nilai_hps', 'tgl_pembuatan']]

# LPSE file (to get LPSE id)
query_lpse = '''SELECT * FROM lpse'''
lpse_src = pd.read_sql_query(query_lpse, database_connection)

# Domain columns for Joining Table
lpse_src["domain"] = lpse_src["url"].apply(lambda row: urlparse(row).netloc)
lpse_src.drop_duplicates(subset=['url'], inplace=True)

# Left Join LPSE and Tender's DataFrame
df_tender_id_lpse = pd.merge(df_tender, lpse_src[['id_lpse', 'domain', 'versi']], how='left',
                                left_on='domain',right_on='domain')

# Rename and Data Type Casting
df_tender_id_lpse.rename(columns={'versi':'versi_lpse','nama_tahapan':'status'},inplace=True)
df_tender_id_lpse['tgl_pembuatan'] = pd.to_datetime(df_tender_id_lpse['tgl_pembuatan'], format='%d-%m-%Y', errors='coerce')

# Jenis Tender's file (to get LPSE id)
query_jenis = '''SELECT * FROM jenis_tender'''
jenis_src = pd.read_sql_query(query_jenis, database_connection)

# Left Join Jenis Tender and Tender's DataFrame
df_tender_id_jenis = pd.merge(df_tender_id_lpse, jenis_src[['id_jenis', 'jenis_tender']], 
                           left_on='jenis_tender', right_on='jenis_tender', how='left')

# Convert Kualifikasi Column
df_tender_id_jenis['kualifikasi'].replace({'Kecil':'1',
                                           'Usaha ( Kecil )':'1',
                                           'Perusahaan Kecil':'1',
                                           'Perusahaan ( Usaha Kecil )':'1',
                                           'Perusahaan ( KECIL )':'1',
                                           'USAHA ( KECIL )':'1',
                                           '( Usaha Kecil )':'1',
                                           'Perusahaan Kecil atau Non Kecil':'1',
                                           'Memiliki Kualifikasi Usaha Kecil':'1',
                                           'Kualifikasi Usaha Kecil':'1',
                                           'Kecil (Minimal Grade 3)':'1',
                                           'Kualifikasi Usaha Kecil (K)':'1',
                                           'Usaha Kecil':'1',
                                           'Usaha kecil':'1',
                                           'KECIL':'1',
                                           'Usaha Non Kecil':'1',
                                           'Perusahaan ( NON KECIL )':'2',
                                           'Non Kecil':'2',
                                           'Usaha (Non Kecil)':'2',
                                           'Usaha ( Non Kecil )':'2',
                                           'Perusahaan (Non Kecil )':'2',
                                           'Perusahaan Non Kecil':'2',
                                           'NON KECIL':'2',
                                           'Besar':'3',
                                           'Menengah' : '4',
                                           'Kualifikasi Usaha Menengah':'4',
                                           'Kecil dan Non Kecil':'5',
                                           'kecil dan non kecil':'5',
                                           'Kualifikasi Usaha Menengah (M1), (M2) maupun Besar (B)':'5',
                                           'Kecil atau Non Kecil':'5',
                                           'Sesuai LDK Dokumen Pemilihan':'6'}, inplace=True)
print('NILAI KUALIFIKASI\n' + str(df_tender_id_jenis.kualifikasi.value_counts()))

# Tender Table Ready to load
tabel_tender = df_tender_id_jenis[['id_tender', 'id_duplikat', 
                                   'id_lpse', 'nama_tender', 'id_jenis',
                                   'tahun_anggaran', 'metode_pemilihan', 'metode_pengadaan',
                                   'metode_evaluasi', 'status', 'alasan', 'versi_lpse', 'nilai_kontrak',
                                   'kualifikasi', 'nilai_hps', 'tgl_pembuatan']]
tabel_tender.tail()

STATUS
Tender Sudah Selesai                                                 47901
Tender Gagal                                                          5590
Seleksi Gagal                                                         2628
Tender Batal                                                          2212
Seleksi Batal                                                         1670
Pengumuman Prakualifikasi                                              102
Evaluasi Dokumen Kualifikasi                                            83
Pengumuman Pascakualifikasi                                             81
Download Dokumen Pemilihan                                              69
Download Dokumen Kualifikasi                                            63
Download Dokumen Pemilihan                                              53
Evaluasi Dokumen Kualifikasi                                            49
Masa Sanggah Prakualifikasi                                             45
Evaluasi Administrasi, Kualifikasi, Teknis, dan Harga                   42
Masa Sanggah                                                            37
Evaluasi Administrasi, Kualifikasi, Teknis, dan Harga                   36
Tidak Ada Jadwal                                                        34
Penandatanganan Kontrak                                                 25
Penetapan Pemenang                                                      12
Kirim Persyaratan Kualifikasi                                           11
Pengumuman Hasil Prakualifikasi                                         10
Surat Penunjukan Penyedia Barang/Jasa                                    8
Pembuktian Kualifikasi                                                   7
Surat Penunjukan Penyedia Barang/Jasa                                    7
Pembukaan Dokumen Penawaran                                              6
Pembuktian Kualifikasi                                                   6
Pembukaan dan Evaluasi Penawaran File I: Administrasi dan Teknis         5
Pembukaan dan Evaluasi Penawaran File II: Harga                          5
Upload Dokumen Penawaran                                                 3
Pembukaan Dokumen Penawaran                                              2
Kirim Persyaratan Kualifikasi                                            2
Klarifikasi dan Negosiasi Teknis dan Biaya                               1
Pemberian Penjelasan                                                     1
Name: nama_tahapan, dtype: int64
NILAI KUALIFIKASI
2    16987
1    12271
4      727
3      505
5      430
Name: kualifikasi, dtype: int64

,id_tender,id_duplikat,id_lpse,nama_tender,id_jenis,tahun_anggaran,metode_pemilihan,metode_pengadaan,metode_evaluasi,status,alasan,versi_lpse,nilai_kontrak,kualifikasi,nilai_hps,tgl_pembuatan
60802,7064,7064,64,Pembangunan Rusunawa Kota Bekasi Lokasi Mabes ...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60803,6064,6064,64,Pembangunan Rusunawa Kota Bandung Lokasi Kodam...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60804,5064,5064,64,Pembangunan Rusunawa Kabupaten Bogor Lokasi Ko...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Gagal,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60805,4064,4064,64,Pembangunan Rusunawa Kota Banda Aceh Lokasi Ko...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60806,19947064,19947064,64,Rehabilitasi Jalan Bangkae - Pangkajene Sidrap...,1,2007.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,27224510243.00,1,32725000000.00,2016-10-26

In [21]:
tabel_tender.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60807 entries, 0 to 60806
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_tender         60807 non-null  int64
 1   id_duplikat       60807 non-null  string
 2   id_lpse           60807 non-null  int64
 3   nama_tender       60807 non-null  object
 4   id_jenis          60807 non-null  int64
 5   tahun_anggaran    60805 non-null  float64
 6   metode_pemilihan  60807 non-null  object
 7   metode_pengadaan  60807 non-null  object
 8   metode_evaluasi   60807 non-null  object
 9   status            60806 non-null  object
 10  alasan            16624 non-null  object
 11  versi_lpse        60807 non-null  object
 12  nilai_kontrak     42743 non-null  object
 13  kualifikasi       30920 non-null  object
 14  nilai_hps         59102 non-null  object
 15  tgl_pembuatan     59101 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(3), object(10), string(1)
memory usage: 7.9+ MB

In [22]:
tabel_tender.id_lpse.unique()

array([64], dtype=int64)

In [23]:
len(tabel_tender.id_lpse.unique())

1

In [24]:
df_id_lpse = pd.DataFrame(tabel_tender.id_lpse.unique(), columns=['id_lpse'])
df_id_lpse.to_excel('id_lpse.xlsx')

In [25]:
tender_src[tender_src.id_tender==159631	]

Empty DataFrame
Columns: [url_lpse, id_duplikat, id_tender, id_rup, nama_tahapan, status_spse, status_evaluasi, alasan, nama_paket, sumber_dana, tgl_pembuatan, k_l_pd, satker, jenis_tender, metode_pengadaan, metode_pemilihan, metode_evaluasi, tahun_anggaran, nilai_kontrak, nilai_pagu, nilai_hps, cara_bayar, lokasi_pekerjaan, kualifikasi, detail_kualifikasi, jumlah_peserta, link_pengumuman_error, domain, status]
Index: []

In [26]:
tabel_tender[tabel_tender.id_lpse.isnull()]

Empty DataFrame
Columns: [id_tender, id_duplikat, id_lpse, nama_tender, id_jenis, tahun_anggaran, metode_pemilihan, metode_pengadaan, metode_evaluasi, status, alasan, versi_lpse, nilai_kontrak, kualifikasi, nilai_hps, tgl_pembuatan]
Index: []

In [27]:
tabel_tender[tabel_tender.nama_tender.isnull()]

Empty DataFrame
Columns: [id_tender, id_duplikat, id_lpse, nama_tender, id_jenis, tahun_anggaran, metode_pemilihan, metode_pengadaan, metode_evaluasi, status, alasan, versi_lpse, nilai_kontrak, kualifikasi, nilai_hps, tgl_pembuatan]
Index: []

In [28]:
tabel_tender[tabel_tender.duplicated(subset='id_tender', keep=False)].sort_values(by=['id_tender']).reset_index(drop=True)

Empty DataFrame
Columns: [id_tender, id_duplikat, id_lpse, nama_tender, id_jenis, tahun_anggaran, metode_pemilihan, metode_pengadaan, metode_evaluasi, status, alasan, versi_lpse, nilai_kontrak, kualifikasi, nilai_hps, tgl_pembuatan]
Index: []

In [29]:
tabel_tender.tail()

,id_tender,id_duplikat,id_lpse,nama_tender,id_jenis,tahun_anggaran,metode_pemilihan,metode_pengadaan,metode_evaluasi,status,alasan,versi_lpse,nilai_kontrak,kualifikasi,nilai_hps,tgl_pembuatan
60802,7064,7064,64,Pembangunan Rusunawa Kota Bekasi Lokasi Mabes ...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60803,6064,6064,64,Pembangunan Rusunawa Kota Bandung Lokasi Kodam...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60804,5064,5064,64,Pembangunan Rusunawa Kabupaten Bogor Lokasi Ko...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Gagal,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60805,4064,4064,64,Pembangunan Rusunawa Kota Banda Aceh Lokasi Ko...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60806,19947064,19947064,64,Rehabilitasi Jalan Bangkae - Pangkajene Sidrap...,1,2007.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,27224510243.00,1,32725000000.00,2016-10-26

In [30]:
tabel_tender[tabel_tender.id_tender==1999]

Empty DataFrame
Columns: [id_tender, id_duplikat, id_lpse, nama_tender, id_jenis, tahun_anggaran, metode_pemilihan, metode_pengadaan, metode_evaluasi, status, alasan, versi_lpse, nilai_kontrak, kualifikasi, nilai_hps, tgl_pembuatan]
Index: []

In [31]:
tes = pd.concat(g for _, g in tabel_tender.groupby("id_tender") if len(g) > 1)
temp = pd.concat(g for _, g in tes.groupby("nama_tender") if len(g) > 1)
temp.to_excel('tes.xlsx')

ValueError: No objects to concatenate

In [32]:
tabel_tender.tail()

,id_tender,id_duplikat,id_lpse,nama_tender,id_jenis,tahun_anggaran,metode_pemilihan,metode_pengadaan,metode_evaluasi,status,alasan,versi_lpse,nilai_kontrak,kualifikasi,nilai_hps,tgl_pembuatan
60802,7064,7064,64,Pembangunan Rusunawa Kota Bekasi Lokasi Mabes ...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60803,6064,6064,64,Pembangunan Rusunawa Kota Bandung Lokasi Kodam...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60804,5064,5064,64,Pembangunan Rusunawa Kabupaten Bogor Lokasi Ko...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Gagal,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60805,4064,4064,64,Pembangunan Rusunawa Kota Banda Aceh Lokasi Ko...,1,2010.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,NaN,NaN,NaN,NaT
60806,19947064,19947064,64,Rehabilitasi Jalan Bangkae - Pangkajene Sidrap...,1,2007.0,Lelang Umum,Pascakualifikasi Satu File,Harga Terendah Sistem Gugur,Tender Sudah Selesai,NaN,4.4u20220808,27224510243.00,1,32725000000.00,2016-10-26

In [33]:
tabel_tender[tabel_tender.id_lpse==1043]

Empty DataFrame
Columns: [id_tender, id_duplikat, id_lpse, nama_tender, id_jenis, tahun_anggaran, metode_pemilihan, metode_pengadaan, metode_evaluasi, status, alasan, versi_lpse, nilai_kontrak, kualifikasi, nilai_hps, tgl_pembuatan]
Index: []

In [34]:
# Import dataframe into MySQL
database_username = 'sigama_tender'
database_password = '5sWrx53vQPcU'
database_ip       = 'sv2.ecc.co.id'
database_name     = 'sigama_tender'
database_connection = sqlalchemy.create_engine('mysql+mysqlconnector://{0}:{1}@{2}/{3}'.
                                               format(database_username, database_password, 
                                                      database_ip, database_name))
database_connection

Engine(mysql+mysqlconnector://sigama_tender:***@sv2.ecc.co.id/sigama_tender)

In [35]:
# Load to DB

tabel_tender.to_sql(con=database_connection, name='tender', if_exists='append', index=False, chunksize=500, method='multi')

# Tabel Detail Tender

In [36]:
query = '''SELECT * FROM wilayah'''
tabel_wilayah = pd.read_sql_query(query, database_connection)
tabel_wilayah

     id_wilayah         wilayah
0            11            Aceh
1            12  Sumatera Utara
2            13  Sumatera Barat
3            14            Riau
4            15           Jambi
..          ...             ...
577        9433      Kab Puncak
578        9434     Kab Dogiyai
579        9435  Kab Intan Jaya
580        9436      Kab Deiyai
581        9471   Kota Jayapura

[582 rows x 2 columns]

In [37]:
# Join id wilayah between LPSE and Tender
df_pengumuman = pd.merge(tender_src[['id_duplikat', 'satker', 'nilai_pagu', 'lokasi_pekerjaan', 'cara_bayar', 'jumlah_peserta', 'domain']],
                        lpse_src[['id_wilayah', 'domain']], how='left', left_on='domain',right_on='domain')
df_pengumuman.drop('domain', axis=1, inplace=True)

# Province column
df_pengumuman['id_wilayah'] = df_pengumuman.id_wilayah.astype('string')
df_pengumuman['id_wilayah_provinsi'] = df_pengumuman['id_wilayah'].str[:2]
df_pengumuman['id_wilayah'] = df_pengumuman.id_wilayah.astype(int)
df_pengumuman['id_wilayah_provinsi'] = df_pengumuman.id_wilayah_provinsi.astype(int)

# Cleaning Package name
list_kolom = ['satker', 'lokasi_pekerjaan']
for i in list_kolom:
    tender_src[i] = tender_src[i].str.strip(', -')

# Join id wilayah between Pengumuman and Wilayah Table (provinces and disticts columns)
tabel_pengumuman = pd.merge(df_pengumuman, tabel_wilayah, how='left', left_on='id_wilayah', right_on='id_wilayah')
tabel_pengumuman = pd.merge(tabel_pengumuman, tabel_wilayah, how='left', left_on='id_wilayah_provinsi', right_on='id_wilayah')

# Rename and Remove Unnecessary Columns
tabel_pengumuman.drop(['id_wilayah_x', 'id_wilayah_provinsi', 'id_wilayah_y'], axis=1, inplace=True)
tabel_pengumuman.rename(columns={'wilayah_x':'kab_pekerjaan', 'wilayah_y':'prov_pekerjaan'}, inplace=True)
nama_kolom = ['id_duplikat', 'satker', 'nilai_pagu', 'lokasi_pekerjaan', 
              'kab_pekerjaan', 'prov_pekerjaan', 'cara_bayar', 'jumlah_peserta']
tabel_pengumuman = tabel_pengumuman.reindex(columns=nama_kolom)
tabel_pengumuman.rename({'id_duplikat':'id_tender'}, axis=1, inplace=True)

tabel_pengumuman[tabel_pengumuman.duplicated(subset='id_tender', keep=False)].sort_values(by=['id_tender']).reset_index(drop=True)

Empty DataFrame
Columns: [id_tender, satker, nilai_pagu, lokasi_pekerjaan, kab_pekerjaan, prov_pekerjaan, cara_bayar, jumlah_peserta]
Index: []

In [40]:
tabel_pengumuman[~tabel_pengumuman.nilai_pagu.isnull()].reset_index(drop=True)

,id_tender,satker,nilai_pagu,lokasi_pekerjaan,kab_pekerjaan,prov_pekerjaan,cara_bayar,jumlah_peserta
0,82617064,OPERASI DAN PEMELIHARAAN SUMBER DAYA AIR CITARUM,5000000000.00,Kabupaten Bandung - Bandung (Kota),Kota Jakarta Selatan,Dki Jakarta,Harga Satuan,36 peserta
1,82608064,486112,1651595000.00,KAB. HALMAHERA TENGAH - Halmahera Tengah (Kab.),Kota Jakarta Selatan,Dki Jakarta,Waktu Penugasan,7 peserta
2,82607064,486112,1916280000.00,KOTA TIDORE KEPULAUAN - Tidore Kepulauan (Kota),Kota Jakarta Selatan,Dki Jakarta,Waktu Penugasan,9 peserta
3,82605064,486112,2025317000.00,KAB. PULAU MOROTAI - Pulau Morotai (Kab.),Kota Jakarta Selatan,Dki Jakarta,Waktu Penugasan,9 peserta
4,82581064,498134,9000000000.00,KAB. CIANJUR - Cianjur (Kab.),Kota Jakarta Selatan,Dki Jakarta,Harga Satuan,39 peserta
...,...,...,...,...,...,...,...,...
59097,1502064,Penyediaan Perumahan,3000000000.00,Kab. Probolinggo - Probolinggo (Kab.)\nKota Pr...,Kota Jakarta Selatan,Dki Jakarta,Harga Satuan,0 peserta
59098,1501064,Penyediaan Perumahan,2500000000.00,"Desa Conggeang Kulon, Kec. Conggeang - Sumedan...",Kota Jakarta Selatan,Dki Jakarta,Harga Satuan,78 peserta
59099,1500064,Penyediaan Perumahan,3700000000.00,Kota Tangerang - Tangerang (Kota)\nKota Tanger...,Kota Jakarta Selatan,Dki Jakarta,Harga Satuan,91 peserta
59100,1499064,Sekretariat Kementerian Perumahan Rakyat,1741464167.00,"Jl. Raden Patah I No. 1, Kebayoran Baru, Jakar...",Kota Jakarta Selatan,Dki Jakarta,Lumsum,61 peserta
59101,19947064,PELAKSANAAN JALAN NASIONAL WILAYAH II PROVINSI...,32800000000.00,Sidrap - Sidenreng Rappang (Kab.),Kota Jakarta Selatan,Dki Jakarta,Harga Satuan,60 peserta

In [39]:
tabel_pengumuman.tail()

,id_tender,satker,nilai_pagu,lokasi_pekerjaan,kab_pekerjaan,prov_pekerjaan,cara_bayar,jumlah_peserta
60802,7064,NaN,NaN,NaN,Kota Jakarta Selatan,Dki Jakarta,NaN,NaN
60803,6064,NaN,NaN,NaN,Kota Jakarta Selatan,Dki Jakarta,NaN,NaN
60804,5064,NaN,NaN,NaN,Kota Jakarta Selatan,Dki Jakarta,NaN,NaN
60805,4064,NaN,NaN,NaN,Kota Jakarta Selatan,Dki Jakarta,NaN,NaN
60806,19947064,PELAKSANAAN JALAN NASIONAL WILAYAH II PROVINSI...,32800000000.00,Sidrap - Sidenreng Rappang (Kab.),Kota Jakarta Selatan,Dki Jakarta,Harga Satuan,60 peserta

In [41]:
# Load to DB

tabel_pengumuman.to_sql(con=database_connection, name='detail_tender',if_exists='append',index=False, chunksize=500, method='multi')

# Tabel RUP

In [42]:
# Import dataframe into MySQL
database_username = 'sigama_tender'
database_password = '5sWrx53vQPcU'
database_ip       = 'sv2.ecc.co.id'
database_name     = 'sigama_tender'
database_connection = sqlalchemy.create_engine('mysql+mysqlconnector://{0}:{1}@{2}/{3}'.
                                               format(database_username, database_password, 
                                                      database_ip, database_name))
database_connection

Engine(mysql+mysqlconnector://sigama_tender:***@sv2.ecc.co.id/sigama_tender)

In [43]:
tabel_rup = tender_src[['id_rup', 'id_duplikat', 'nama_paket', 'sumber_dana']]
tabel_rup.rename({'id_duplikat':'id_tender'}, axis=1, inplace=True)
# Cleaning Package name
list_kolom = ['nama_paket', 'sumber_dana']
for i in list_kolom:
    tender_src[i] = tender_src[i].str.strip(', -')
tabel_rup.tail()

C:\Users\Asus\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,id_rup,id_tender,nama_paket,sumber_dana
60802,NaN,7064,Pembangunan Rusunawa Kota Bekasi Lokasi Mabes ...,NaN
60803,NaN,6064,Pembangunan Rusunawa Kota Bandung Lokasi Kodam...,NaN
60804,NaN,5064,Pembangunan Rusunawa Kabupaten Bogor Lokasi Ko...,NaN
60805,NaN,4064,Pembangunan Rusunawa Kota Banda Aceh Lokasi Ko...,NaN
60806,NaN,19947064,Rehabilitasi Jalan Bangkae - Pangkajene Sidrap...,APBN

In [44]:
tabel_rup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60807 entries, 0 to 60806
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_rup       26085 non-null  float64
 1   id_tender    60807 non-null  string
 2   nama_paket   60807 non-null  object
 3   sumber_dana  59051 non-null  object
dtypes: float64(1), object(2), string(1)
memory usage: 1.9+ MB

In [45]:
# Load to DB

tabel_rup.to_sql(con=database_connection, name='rup',if_exists='append',index=False, chunksize=500, method='multi')

# Tabel Syarat Kualifikasi

In [46]:
syarat_kualifikasi = tender_src[['id_duplikat', 'detail_kualifikasi']]
syarat_kualifikasi.head()

  id_duplikat                                 detail_kualifikasi
0    82617064  <strong>Persyaratan Kualifikasi Administrasi/L...
1    82608064  <strong>Persyaratan Kualifikasi</strong>, \n, ...
2    82607064  <strong>Persyaratan Kualifikasi</strong>, \n, ...
3    82605064  <strong>Persyaratan Kualifikasi</strong>, \n, ...
4    82581064  <strong>Persyaratan Kualifikasi Administrasi/L...

In [47]:
syarat_kualifikasi[syarat_kualifikasi['id_duplikat'].str.contains("1999\.")]

Empty DataFrame
Columns: [id_duplikat, detail_kualifikasi]
Index: []

In [48]:
def type_detection(detail_kualifikasi):
    if ("Kualifikasi Teknis" in str(detail_kualifikasi) and "Kualifikasi Administrasi" in str(detail_kualifikasi)) or ("Teknis" in str(detail_kualifikasi) and "Administrasi" in str(detail_kualifikasi)):
        return "Semua"
    elif "Kualifikasi Teknis" in str(detail_kualifikasi) or "Teknis" in str(detail_kualifikasi):
        return "Teknis"
    elif "Kualifikasi Administrasi" in str(detail_kualifikasi) or "Administrasi" in str(detail_kualifikasi):
        return "Administrasi"
    else:
        return "Semua"
syarat_kualifikasi["kategori"] = syarat_kualifikasi.detail_kualifikasi.apply(lambda x: type_detection(x))

C:\Users\Asus\AppData\Local\Temp/ipykernel_1212/1800176701.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  syarat_kualifikasi["kategori"] = syarat_kualifikasi.detail_kualifikasi.apply(lambda x: type_detection(x))

In [49]:
syarat_kualifikasi.kategori.value_counts()

Semua           55725
Teknis           3993
Administrasi     1089
Name: kategori, dtype: int64

In [50]:
syarat_kualifikasi.tail()

      id_duplikat                                 detail_kualifikasi kategori
60802        7064                                                NaN    Semua
60803        6064                                                NaN    Semua
60804        5064                                                NaN    Semua
60805        4064                                                NaN    Semua
60806    19947064  <table class="table table-sm">\n<tbody><tr val...    Semua

In [51]:
# syarat_kualifikasi = tender_src[['id_duplikat', 'detail_kualifikasi']]

# # teknis OR administrasi
# all_kat = syarat_kualifikasi.loc[syarat_kualifikasi['detail_kualifikasi'].str.contains('Kualifikasi Teknis|Kualifikasi Administrasi', flags=re.IGNORECASE, regex=True, na=False)]
# teknis_unfix = all_kat.loc[all_kat['detail_kualifikasi'].str.contains('Kualifikasi Teknis', flags=re.IGNORECASE, regex=True)]
# administrasi_unfix = all_kat.loc[all_kat['detail_kualifikasi'].str.contains('Kualifikasi Administrasi', flags=re.IGNORECASE, regex=True)]

# # teknis fix
# common = all_kat.merge(administrasi_unfix,on=['id_duplikat'])
# df_teknis = all_kat[(~all_kat.id_duplikat.isin(common.id_duplikat))]

# # administrasi fix
# common = all_kat.merge(teknis_unfix,on=['id_duplikat'])
# df_administrasi = all_kat[(~all_kat.id_duplikat.isin(common.id_duplikat))]

# # add label
# def label_race (row):
#    if row["id_duplikat"] in df_teknis["id_duplikat"].unique():
#       return 'Teknis'
#    if row["id_duplikat"] in df_administrasi["id_duplikat"].unique():
#       return 'Administrasi'
#    return 'Semua'

# syarat_kualifikasi['kategori'] = syarat_kualifikasi.apply(lambda row: label_race(row), axis=1)
syarat_kualifikasi.rename(columns={'detail_kualifikasi':'syarat'}, inplace=True)
print('NILAI KATEGORI\n' + str(syarat_kualifikasi.kategori.value_counts()))
tabel_syarat_kualifikasi = syarat_kualifikasi[['id_duplikat', 'kategori', 'syarat']]
tabel_syarat_kualifikasi.rename({'id_duplikat':'id_tender'}, axis=1, inplace=True)

tabel_syarat_kualifikasi.tail()

NILAI KATEGORI
Semua           55725
Teknis           3993
Administrasi     1089
Name: kategori, dtype: int64

C:\Users\Asus\anaconda3\lib\site-packages\pandas\core\frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

      id_tender kategori                                             syarat
60802      7064    Semua                                                NaN
60803      6064    Semua                                                NaN
60804      5064    Semua                                                NaN
60805      4064    Semua                                                NaN
60806  19947064    Semua  <table class="table table-sm">\n<tbody><tr val...

In [52]:
tabel_syarat_kualifikasi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60807 entries, 0 to 60806
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id_tender  60807 non-null  string
 1   kategori   60807 non-null  object
 2   syarat     58961 non-null  object
dtypes: object(2), string(1)
memory usage: 1.4+ MB

In [53]:
# Load to DB
tabel_syarat_kualifikasi.to_sql(con=database_connection, name='syarat_kualifikasi',if_exists='append',index=False,chunksize=500, method='multi')